### ISSUE TITLE
不要な記述がない

### ISSUE THREAD

**Issue by washogo** [Shuheitkhs/emompath#10]
src/app/api/auth/signin-google/route.ts
src/app/api/auth/signup/route.ts
src/app/auth/signin/page.tsx
src/app/auth/signup/page.tsx
src/components/molecules/Counter.tsx

**Comment by Shuheitkhs** [comment]
他のページやコンポーネントも確認して不要な記述を削除しています。

**Comment by washogo** [comment]
不要と思われるconsole.logの利用箇所
- src/app/page.tsx
- src/app/api/auth/signin-google/route.ts
- src/app/auth/signin/page.tsx
- src/app/emoms/create/page.tsx
- src/components/CompleteDialog.tsx

**Comment by Shuheitkhs** [comment]
指摘を受けたconsole.logの削除を行いました。
